name: CI

on:
  push:
    branches: [ master, v1 ]
  pull_request:
    branches: [ master, v1 ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        go-version: ["1.19.x", "oldstable", "stable"]

    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v7

    - name: Set up Go
      uses: actions/setup-go@v7
      with:
        go-version: ${{ matrix.go-version }}

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test -v -race ./...
